<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Fruit: An Overview</title>
	<link rel="stylesheet" href="css/styles.css">
	<link rel="stylesheet" href="css/navigation.css">
	<link rel="stylesheet" href="css/banner.css">
	<link rel="stylesheet" href="sss/sss.css">
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
	<link rel="stylesheet" href="/resources/demos/style.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />  
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> 
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css">
     
		   
</head>

